# Generated by Django 2.2.3 on 2019-07-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('balance', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('wrong_pin_counter', models.IntegerField()),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'card_account',
                'abstract': False,
            },
        ),
    ]
