# Generated by Django 2.2.3 on 2019-07-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardaccount',
            name='wrong_pin_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('operation_code', models.PositiveSmallIntegerField(choices=[(1, 'Balance'), (2, 'Withdraw')])),
                ('withdraw_amount', models.IntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash_machine.CardAccount')),
            ],
            options={
                'db_table': 'transaction',
                'abstract': False,
            },
        ),
    ]
